# Model hyperparameters
model:
  use_performer: True
  image_size: 224
  patch_size: 8
  num_classes: 200
  model_depth: 4
  model_dim: 192
  heads: 8
  dim_head: 32
  dropout: 0.3
  kernel_fn: "ReLU"
  proj_type: "default"  # TODO: change this! ['disabled', 'default', 'learnable']
  redraw_interval: 2500
  random_features: 4
  feedforward_dim_multiplier: 4



# Training hyperparameters
train:
  batch_size: 256
  test_batch_size: 128
  epochs: 30
  lr: 0.0005
  gamma: 0.7
  optimizer: "AdamW"
  weight_decay: 0.01
  scheduler: "CosineAnnealingLR"
  T_max: 30
  save_model: True

# Dataset settings
dataset:
  name: "TinyImageNet"
  small: True
  transform: 
    - type: "Resize"
      size: [224, 224]
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Wandb configuration
wandb:
  project: "vit-performer-tiny-imagenet"
  use_wandb: true
  log_interval: 50
  dry_run: False

# Device settings
device:
  no_cuda: False
  no_mps: False
  seed: 1



