# Model hyperparameters
model:
  use_performer: True
  print_model: False
  image_size: 32
  patch_size: 4
  num_classes: 10
  model_depth: 4
  model_dim: 128
  dim_head: 64
  heads: 4
  dropout: 0.2
  kernel_fn: "exp" # ReLU Softmax
  proj_type: "default"  # TODO: change this! ['disabled', 'default', 'learnable']
  redraw_interval: 2500
  random_features: 8
  feedforward_dim_multiplier: 2

# Training hyperparameters
train:
  batch_size: 256
  test_batch_size: 1000
  epochs: 100
  lr: 0.0005
  gamma: 0.7
  optimizer: "AdamW"
  weight_decay: 0.1
  scheduler: "CosineAnnealingLR"
  T_max: 200
  save_model: True

# Dataset settings
dataset:
  name: "CIFAR10"
  transform: 
    - type: "ToTensor"
    - type: "Normalize"
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

# Wandb configuration
wandb:
  project: "vit-performer"
  use_wandb: true
  log_interval: 10
  dry_run: false

# Device settings
device:
  no_cuda: false
  no_mps: false
  seed: 1
